//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVotaciones.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidatos
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Cargo { get; set; }
        public Nullable<int> PlanchaId { get; set; }
    
        public virtual Planchas Planchas { get; set; }
    }
}
